// Mocks generated by Mockito 5.4.4 from annotations
// in e5d_assesment/test/topup_tests.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:e5d_assesment/features/topup/domain/model/abstract_topup_request.dart'
    as _i7;
import 'package:e5d_assesment/features/topup/domain/model/top_up_transaction.dart'
    as _i6;
import 'package:e5d_assesment/features/topup/domain/repository/abstract_topup_repository.dart'
    as _i3;
import 'package:e5d_assesment/features/topup/presentation/state/get_transactions_ui_states.dart'
    as _i8;
import 'package:e5d_assesment/features/topup/presentation/state/topup_ui_states.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AbstractTopUpRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbstractTopUpRepository extends _i1.Mock
    implements _i3.AbstractTopUpRepository {
  MockAbstractTopUpRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.TopUpUiStates, _i6.TopUpTransaction>> topUp(
          _i7.AbstractTopUpRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #topUp,
          [request],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.TopUpUiStates, _i6.TopUpTransaction>>.value(
            _FakeEither_0<_i5.TopUpUiStates, _i6.TopUpTransaction>(
          this,
          Invocation.method(
            #topUp,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.TopUpUiStates, _i6.TopUpTransaction>>);

  @override
  _i4.Future<
      _i2.Either<_i8.GetTransactionsUiStates,
          List<_i6.TopUpTransaction>>> getTransactions() => (super.noSuchMethod(
        Invocation.method(
          #getTransactions,
          [],
        ),
        returnValue: _i4.Future<
            _i2.Either<_i8.GetTransactionsUiStates,
                List<_i6.TopUpTransaction>>>.value(_FakeEither_0<
            _i8.GetTransactionsUiStates, List<_i6.TopUpTransaction>>(
          this,
          Invocation.method(
            #getTransactions,
            [],
          ),
        )),
      ) as _i4.Future<
          _i2.Either<_i8.GetTransactionsUiStates, List<_i6.TopUpTransaction>>>);
}
